[TASK] Ensure php files contain correct legal file header
Core php file header check got silently be disabled. Since
then the one or other file header error has slipped into
the core. It also pops up from time to time in reviews of
patches that file headers are missing (or are wrong).

This change ensures that file headers are checked again
and can be fixed by given contributers the proper tools
at hand.

Changes:

* add cglFixMyCommitFileHeader.(sh|bat)
* add cglHeader and cglHeaderGit to runTests.sh along
  with proper help text
* extend pre-commit hook to execute both fixer scripts
  side-by-side with error output and fixing possibility
* fix minor issue with header comment php-cs-fixer config

Additionally the cglHeader check is added to gitlab workflow
pre-merge (commit files) and nightly (all files).

Slipped in errors has been fixed with a dedicated change #98204.

Resolves: #98203
Related: #98204
Releases: main
Change-Id: I9567d1dcf8fb53d4901a575213c0ff16dc33ffd2
Reviewed-on: https://review.typo3.org/c/Packages/TYPO3.CMS/+/75549
Tested-by: core-ci <typo3@b13.com>
Tested-by: Benjamin Franzke <bfr@qbus.de>
Tested-by: Christian Kuhn <lolli@schwarzbu.ch>
Tested-by: Andreas Fernandez <a.fernandez@scripting-base.de>
Tested-by: Stefan Bürk <stefan@buerk.tech>
Reviewed-by: Benjamin Franzke <bfr@qbus.de>
Reviewed-by: Christian Kuhn <lolli@schwarzbu.ch>
Reviewed-by: Andreas Fernandez <a.fernandez@scripting-base.de>
Reviewed-by: Stefan Bürk <stefan@buerk.tech>

diff --git a/Build/git-hooks/unix+mac/pre-commit b/Build/git-hooks/unix+mac/pre-commit
--- a/Build/git-hooks/unix+mac/pre-commit
+++ b/Build/git-hooks/unix+mac/pre-commit
@@ -1,26 +1,34 @@
 #!/usr/bin/env bash
 
 # pre-commit hook
-# - check if staged files adhere to Coding Guidelines
+# - check if staged files adhere to Coding Guidelines and have proper file header
 # - abort on error:no for now, override with environment variable TYPO3_GIT_HOOK_ABORT_ON_ERROR
 #
 # Dependencies:
 #   uses: Build/Scripts/cglFixMyCommit.sh
 #
 
+USE_EXIT_CODE=0
 script=Build/Scripts/cglFixMyCommit.sh
+scriptFileHeader=Build/Scripts/cglFixMyCommitFileHeader.sh
 
 ABORT_ON_ERROR="no"
 ERROR_TEXT="\n"
 ERROR_CODE=0
+ERROR_CODE_FILE_HEADER=0
 
 if [ -z "${TYPO3_GIT_HOOK_ABORT_ON_ERROR+x}" ]; then
     ABORT_ON_ERROR=${TYPO3_GIT_HOOK_ABORT_ON_ERROR}
 fi
 
 if [ ! -x $script ];then
-    "echo "$script does not exist or is not executable"
-    "exit 0
+    echo "$script does not exist or is not executable"
+    exit 0
+fi
+
+if [ ! -x $scriptFileHeader ];then
+    echo "$scriptFileHeader does not exist or is not executable"
+    exit 0
 fi
 
 # call script with -f <cache> parameter: check files in git cache (staging area)
@@ -28,21 +36,42 @@ fi
 $script -f cache -n
 ERROR_CODE=$?
 
-
 if [ ${ERROR_CODE} -ne 0 ];then
-     echo -e "\n-----------------------------------------------------------------\n"
-     echo -e "  >> ERROR: There was a coding guideline problem in one or more of  "
-     echo -e "              your php files.                                       "
-     echo -e "   Please refer to [1] for details on the coding guidelines         "
-     echo -e "   Please refer to [2] for details on contribution                  "
-     echo -e "   [1] https://docs.typo3.org/typo3cms/CoreApiReference/CodingGuidelines/Index.html"
-     echo -e "   [2] https://docs.typo3.org/typo3cms/ContributionWorkflowGuide/   "
-     echo -e "------------------------------------------------------------------\n"
-     if [[ ${ABORT_ON_ERROR} == "yes" ]];then
-         echo -e "   Your commit is being aborted ... Fix and try again!          "
-         exit 1
-     else
-         echo -e "   You must fix this and then commit again (git commit --amend) "
-     fi
+    echo -e "\n-----------------------------------------------------------------\n"
+    echo -e "  >> ERROR: There was a coding guideline problem in one or more of  "
+    echo -e "              your php files.                                       "
+    echo -e "   Please refer to [1] for details on the coding guidelines         "
+    echo -e "   Please refer to [2] for details on contribution                  "
+    echo -e "   [1] https://docs.typo3.org/typo3cms/CoreApiReference/CodingGuidelines/Index.html"
+    echo -e "   [2] https://docs.typo3.org/typo3cms/ContributionWorkflowGuide/   "
+    echo -e "------------------------------------------------------------------\n"
+    if [[ ${ABORT_ON_ERROR} == "yes" ]];then
+        echo -e "   Your commit is being aborted ... Fix and try again!          "
+        USE_EXIT_CODE=1
+    else
+        echo -e "   You must fix this and then commit again (git commit --amend) "
+    fi
 fi
-exit 0
+
+$scriptFileHeader -f cache -n
+ERROR_CODE_FILE_HEADER=$?
+
+if [ ${ERROR_CODE_FILE_HEADER} -ne 0 ];then
+
+    echo -e "\n-----------------------------------------------------------------\n"
+    echo -e "  >> ERROR: There was a missing or wrong php file header in one or  "
+    echo -e "               more of your php files.                              "
+    echo -e "   Please refer to [1] for details on the coding guidelines         "
+    echo -e "   Please refer to [2] for details on contribution                  "
+    echo -e "   [1] https://docs.typo3.org/typo3cms/CoreApiReference/CodingGuidelines/Index.html"
+    echo -e "   [2] https://docs.typo3.org/typo3cms/ContributionWorkflowGuide/   "
+    echo -e "------------------------------------------------------------------\n"
+    if [[ ${ABORT_ON_ERROR} == "yes" ]];then
+        echo -e "   Your commit is being aborted ... Fix and try again!          "
+        USE_EXIT_CODE=1
+    else
+        echo -e "   You must fix this and then commit again (git commit --amend) "
+    fi
+fi
+
+exit ${USE_EXIT_CODE}
